module.exports = {
  salonService: require("./salon.service"),
  mailService: require("./mail.service"),
  salonOnboardingService: require("./salon-onboarding.service"),
  authService: require("./auth.service"),
  staffService: require("./staff.service"),
  categoryService: require("./category.service"),
  serviceService: require("./service.service"),
  staffServicesService: require("./staff-service.service"),
  uploadService: require("./upload.service"),
  holidayService: require("./holiday.service"),
  cartService: require("./cart.service"),
  bookingService: require("./booking.service"),
  customerService: require("./customer.service"),
  paymentService: require("./payment.service"),
  itemsCategoryService: require("./items-category.service"),
  inventoryItemService: require("./inventory-item.service"),
  inventoryTransactionService: require("./inventory-transaction.service"),
  reconciliationService: require("./reconciliation.service"),
  stripeConnectService: require("./stripe-connect.service"),
};
